package com.yash.pms.view;

import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

import com.yash.pms.dao.PartnerDao;
import com.yash.pms.model.Partner;
import com.yash.pms.util.PartnerConstants;

public class PartnerAddUpdate extends javax.swing.JFrame {

	// Variables declaration - do not modify//GEN-BEGIN:variables

	private String partnerId;
	private String action;

	private javax.swing.JLabel jL_fullname;
	private javax.swing.JLabel jL_orgtype;
	private javax.swing.JLabel jL_org;
	private javax.swing.JLabel jL_resources;
	private javax.swing.JLabel jL_city;
	private javax.swing.JLabel jL_state;
	private javax.swing.JLabel jL_zipcode;
	private javax.swing.JLabel jL_mobile;
	private javax.swing.JLabel jL_email;

	private javax.swing.JComboBox<String> combostate;
	private javax.swing.JComboBox<String> comboorgtype1;

	private javax.swing.JLabel h;
	private javax.swing.JButton jB_close;
	private javax.swing.JButton jB_addpartner;
	private javax.swing.JButton jB_updatepartner;
	private javax.swing.JButton jB_clear;
	private javax.swing.JButton jB_cancel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextArea txtPartnerInfo;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JLabel jLabel8;

	private javax.swing.JLabel lblemail;

	private javax.swing.JTextField txtfullname;

	private javax.swing.JTextField txtcity;
	private javax.swing.JTextField txtaddres;
	private javax.swing.JTextField txtzipcode;
	private javax.swing.JTextField txtemail;
	private javax.swing.JTextField txtmob;
	private javax.swing.JTextField txtorg;

	private javax.swing.JLabel lblnote;

	/**
	 * Creates new form CustomerCheckIn
	 */
	public PartnerAddUpdate(String partner_id) {

		initComponents();
		txtfullname.requestFocus();
		jB_addpartner.setVisible(false);
		this.jB_clear.setVisible(false);
		this.partnerId = partner_id;
		jB_updatepartner.setVisible(true);
		jB_cancel.setVisible(true);

		addFormDadata(partner_id);

	}

	/**
	 * Creates new form CustomerCheckIn
	 */
	public PartnerAddUpdate() {
		initComponents();
		txtfullname.requestFocus();

	}

	public void addFormDadata(String partner_id) {
		System.out.println("partner id val to update:" + partner_id);
		try {
			Partner p = PartnerDao.getPartnerById(partner_id);
			txtfullname.setText(p.getFullName());
			txtorg.setText(p.getOrgName());
			comboorgtype1.setSelectedItem(p.getOrgType());
			txtPartnerInfo.setText(p.getResources());
			txtaddres.setText(p.getAddress());
			combostate.setSelectedItem(p.getState());
			txtcity.setText(p.getCity());
			txtzipcode.setText(p.getZipCode());
			txtemail.setText(p.getEmail());
			txtmob.setText(p.getMobile());

		} catch (Exception ex) {
			ex.printStackTrace();
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblnote = new javax.swing.JLabel();

		jL_fullname = new javax.swing.JLabel();
		jL_orgtype = new javax.swing.JLabel();
		jL_resources = new javax.swing.JLabel();

		jLabel1 = new javax.swing.JLabel();

		jL_org = new javax.swing.JLabel();
		jL_mobile = new javax.swing.JLabel();
		jL_email = new javax.swing.JLabel();

		txtorg = new javax.swing.JTextField();
		txtfullname = new javax.swing.JTextField();

		txtcity = new javax.swing.JTextField();

		txtmob = new javax.swing.JTextField();
		txtemail = new javax.swing.JTextField();

		txtzipcode = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		txtaddres = new javax.swing.JTextField();

		jL_city = new javax.swing.JLabel();

		jL_state = new javax.swing.JLabel();
		comboorgtype1 = new javax.swing.JComboBox<>();
		jL_zipcode = new javax.swing.JLabel();

		combostate = new javax.swing.JComboBox<>();

		jB_addpartner = new javax.swing.JButton();
		jB_updatepartner = new javax.swing.JButton();
		jB_close = new javax.swing.JButton();
		jB_clear = new javax.swing.JButton();
		jB_cancel = new javax.swing.JButton();
		lblemail = new javax.swing.JLabel();
		h = new javax.swing.JLabel();

		txtPartnerInfo = new javax.swing.JTextArea();
		jScrollPane1 = new javax.swing.JScrollPane();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setLocation(new java.awt.Point(0, 0));
		setUndecorated(true);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
		setLocation(300, 200);

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(240, 240, 240));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N
		jLabel1.setText("Partner Details");
		getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 220, 70));

		jL_orgtype.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jL_orgtype.setForeground(new java.awt.Color(255, 255, 255));
		jL_orgtype.setText("Organisation Type");
		getContentPane().add(jL_orgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 380, 35));

		comboorgtype1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		comboorgtype1.setModel(new javax.swing.DefaultComboBoxModel<>(PartnerConstants.Orgtype));
		getContentPane().add(comboorgtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 35));

		jL_org.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jL_org.setForeground(new java.awt.Color(255, 255, 255));
		jL_org.setText("Organisation Name");
		getContentPane().add(jL_org, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 291, 36));

		txtorg.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
		txtorg.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				txtnameFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				txtnameFocusLost(evt);
			}
		});
		txtorg.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				txtnameKeyPressed(evt);
			}
		});
		getContentPane().add(txtorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 350, 40));

		jL_fullname.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jL_fullname.setForeground(new java.awt.Color(255, 255, 255));
		jL_fullname.setText("Full Name");
		getContentPane().add(jL_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 380, 35));

		txtfullname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
		txtfullname.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				txtnameFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				txtnameFocusLost(evt);
			}
		});
		txtfullname.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				txtnameKeyPressed(evt);
			}
		});
		getContentPane().add(txtfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 390, 40));

		jL_email.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jL_email.setForeground(new java.awt.Color(255, 255, 255));
		jL_email.setText("Email");
		getContentPane().add(jL_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 380, 37));

		txtemail.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
		txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				txtemailFocusLost(evt);
			}
		});
		txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				txtemailKeyPressed(evt);
			}

			public void keyReleased(java.awt.event.KeyEvent evt) {
				txtemailKeyReleased(evt);
			}

			public void keyTyped(java.awt.event.KeyEvent evt) {
				txtemailKeyTyped(evt);
			}
		});
		getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 390, 40));

		jL_mobile.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jL_mobile.setForeground(new java.awt.Color(255, 255, 255));
		jL_mobile.setText("Mobile Number");
		getContentPane().add(jL_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 291, 36));

		txtmob.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
		txtmob.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				txtmobFocusLost(evt);
			}
		});
		txtmob.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				txtmobKeyPressed(evt);
			}
		});
		getContentPane().add(txtmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 300, 40));

		jL_resources.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jL_resources.setForeground(new java.awt.Color(255, 255, 255));
		jL_resources.setText("Resources");
		getContentPane().add(jL_resources, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 294, 40));

		txtPartnerInfo.setEditable(true);
		txtPartnerInfo.setColumns(20);
		txtPartnerInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		txtPartnerInfo.setRows(5);

		jScrollPane1.setViewportView(txtPartnerInfo);

		getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 400, 100));

		jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("Address");
		getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 294, 40));

		txtaddres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		txtaddres.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				txtaddresFocusLost(evt);
			}
		});
		txtaddres.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				txtaddresMouseClicked(evt);
			}
		});
		txtaddres.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtaddresActionPerformed(evt);
			}
		});
		getContentPane().add(txtaddres, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 294, 40));

		jL_city.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jL_city.setForeground(new java.awt.Color(255, 255, 255));
		jL_city.setText("City");
		getContentPane().add(jL_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 294, 40));

		txtcity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		txtcity.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				txtaddresFocusLost(evt);
			}
		});
		txtcity.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				txtaddresMouseClicked(evt);
			}
		});
		txtcity.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtaddresActionPerformed(evt);
			}
		});
		getContentPane().add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 294, 40));

		jL_state.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jL_state.setForeground(new java.awt.Color(255, 255, 255));
		jL_state.setText("State");
		getContentPane().add(jL_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 340, 40));

		combostate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		combostate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", 
			    "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", 
			    "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", 
			    "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", 
			    "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", 
			    "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", 
			    "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"}));
		getContentPane().add(combostate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 350, 40));

		jL_zipcode.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jL_zipcode.setForeground(new java.awt.Color(255, 255, 255));
		jL_zipcode.setText("Postal Code");
		getContentPane().add(jL_zipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 294, 40));

		txtzipcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		txtzipcode.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				txtaddresFocusLost(evt);
			}
		});
		txtzipcode.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				txtaddresMouseClicked(evt);
			}
		});
		txtzipcode.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtaddresActionPerformed(evt);
			}
		});
		getContentPane().add(txtzipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 150, 40));

		jB_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close-icon-s.png"))); // NOI18N
		jB_close.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		getContentPane().add(jB_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 40, 40));

		jB_addpartner.setBackground(new java.awt.Color(255, 0, 102));
		jB_addpartner.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jB_addpartner.setForeground(new java.awt.Color(255, 255, 255));
		jB_addpartner.setText("Add Partner");
		jB_addpartner.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton2MouseReleased(evt);
			}
		});
		jB_addpartner.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		getContentPane().add(jB_addpartner, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, -1, 40));

		jB_updatepartner.setBackground(new java.awt.Color(255, 0, 102));
		jB_updatepartner.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jB_updatepartner.setForeground(new java.awt.Color(255, 255, 255));
		jB_updatepartner.setText("Update Partner");
		jB_updatepartner.setVisible(false);
		jB_updatepartner.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton2MouseReleased(evt);
			}
		});
		jB_updatepartner.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jB_updateActionPerformed(evt);
			}
		});
		getContentPane().add(jB_updatepartner, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, -1, 40));

		jB_clear.setBackground(new java.awt.Color(153, 0, 51));
		jB_clear.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jB_clear.setForeground(new java.awt.Color(255, 255, 255));
		jB_clear.setText("Clear");

		jB_clear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		getContentPane().add(jB_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 90, 40));

		jB_cancel.setBackground(new java.awt.Color(153, 0, 51));
		jB_cancel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
		jB_cancel.setForeground(new java.awt.Color(255, 255, 255));
		jB_cancel.setText("Close");
		jB_cancel.setVisible(false);
		jB_cancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jB_cancelActionPerformed(evt);
			}
		});
		getContentPane().add(jB_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 640, 125, 40));

		lblemail.setForeground(new java.awt.Color(204, 0, 0));
		lblemail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 390, 20));

		lblnote.setForeground(new java.awt.Color(204, 0, 0));
		lblnote.setFont(new java.awt.Font("Verdana", 1, 18));
		lblnote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		// lblnote.setFont(new java.awt.Font("Verdana", 1, 18));)
		lblnote.setText("* All Fields are required");
		getContentPane().add(lblnote, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, 390, 30));

		h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-kmk.jpg"))); // NOI18N
		getContentPane().add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 770));
		txtorg.requestFocus(true);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		dispose(); // TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed

		txtmob.setText("");

		txtemail.setText("");
		txtaddres.setText("");
		txtcity.setText("");
		txtmob.setText("");

		txtfullname.setText("");
		txtorg.setText("");
		txtPartnerInfo.setText("");

		txtemail.setText("");
		txtaddres.setText("");

		txtzipcode.setText("");

		// TODO add your handling code here:
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jB_cancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// return to ManagePartners Screen
		new ManagePartner().setVisible(true);
		this.setVisible(false);

	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		if (txtfullname.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtfullname.requestFocus();
		} else if (txtmob.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtmob.requestFocus();
		} else if (txtemail.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtemail.requestFocus();
		} else if (txtaddres.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtaddres.requestFocus();
		} else if (txtmob.getText().length() != 10) {
			JOptionPane.showMessageDialog(this, "Mobile Number Should be 10 Digit.");
		} else if (txtPartnerInfo.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Resources is required");
		} else if (txtorg.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtorg.requestFocus();

		} else if (txtcity.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtcity.requestFocus();
		} else {

			try {

				boolean partnerFound = PartnerDao.checkPartnerAlreadyExist(txtfullname.getText(),
						comboorgtype1.getItemAt(comboorgtype1.getSelectedIndex()), txtorg.getText());

				if (partnerFound) {
					JOptionPane.showMessageDialog(this, "Partner Details Already Exist");
				} else {
					try {
						System.out.println("partner not exist , adding partner");

						try {
							int count = PartnerDao.createPartner(txtfullname.getText(),
									comboorgtype1.getItemAt(comboorgtype1.getSelectedIndex()), txtorg.getText(),
									txtemail.getText(), txtmob.getText(), txtPartnerInfo.getText(), txtaddres.getText(),
									combostate.getItemAt(combostate.getSelectedIndex()), txtcity.getText(),
									txtzipcode.getText());

							JOptionPane.showMessageDialog(this, "Partner is Added");

						} catch (Exception ex) {

							JOptionPane.showMessageDialog(this,
									"SQL Exception while saving partner information is not valied");
							ex.printStackTrace();
						}
					} catch (Exception e) {
						JOptionPane.showMessageDialog(this, "Error while saving partner information is not valied");
						e.printStackTrace();
					}

				}

			} catch (Exception ex) {
				// Logger.getLogger(Record.class.getName()).log(Level.SEVERE, null, ex);
				ex.printStackTrace();
			}
		}

	}// GEN-LAST:event_jButton2ActionPerformed

	private void jB_updateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		if (txtfullname.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtfullname.requestFocus();
		} else if (txtmob.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtmob.requestFocus();
		} else if (txtemail.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtemail.requestFocus();
		} else if (txtaddres.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "All Field is Requied");
			txtaddres.requestFocus();
		} else if (txtmob.getText().length() != 10) {
			JOptionPane.showMessageDialog(this, "Mobile Number Should be 10 Digit.");
		}

		else {

			try {
				int count = PartnerDao.updatePartner(txtfullname.getText(),
						comboorgtype1.getItemAt(comboorgtype1.getSelectedIndex()), txtorg.getText(), txtemail.getText(),
						txtmob.getText(), txtPartnerInfo.getText(), txtaddres.getText(),
						combostate.getItemAt(combostate.getSelectedIndex()), txtcity.getText(), txtzipcode.getText(),
						partnerId);

				JOptionPane.showMessageDialog(this, "Partner is Successfully Updated");
				// s();
				// txtprice.setText("");
				// txtno.setText("");

			} catch (Exception ex) {

				JOptionPane.showMessageDialog(this,
						"Error while updating partner information , please check and retry !!");
				ex.printStackTrace();
			}
		}

	}

	private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MouseReleased
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton2MouseReleased

	private void txtaddresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtaddresActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtaddresActionPerformed

	private void txtaddresMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_txtaddresMouseClicked

		// TODO add your handling code here:
	}// GEN-LAST:event_txtaddresMouseClicked

	private void txtnameFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtnameFocusGained

	}// GEN-LAST:event_txtnameFocusGained

	private void txtmobFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtmobFocusLost
		// TODO add your handling code here:
	}// GEN-LAST:event_txtmobFocusLost

	private void txtemailFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtemailFocusLost
		// TODO add your handling code here:
	}// GEN-LAST:event_txtemailFocusLost

	private void txtaddresFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtaddresFocusLost
		// TODO add your handling code here:
	}// GEN-LAST:event_txtaddresFocusLost

	private void txtnameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtnameFocusLost
	}// GEN-LAST:event_txtnameFocusLost

	private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtnameKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER)
			txtmob.requestFocus();// TODO add your handling code here:
	}// GEN-LAST:event_txtnameKeyPressed

	private void txtmobKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtmobKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER)
			txtemail.requestFocus(); // TODO add your handling code here:
	}// GEN-LAST:event_txtmobKeyPressed

	private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtemailKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER)
			txtmob.requestFocus(); // TODO add your handling code here:
	}// GEN-LAST:event_txtemailKeyPressed

	private void txtemailKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtemailKeyTyped
		// TODO add your handling code here:
	}// GEN-LAST:event_txtemailKeyTyped

	private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtemailKeyReleased
		txtemail.setText(txtemail.getText().toLowerCase());

		int a = txtemail.getText().indexOf('@');
		int b = txtemail.getText().length();
		if (a == -1) {
			lblemail.setText("Invalied Email id");
		} else if (b > a + 1) {
			String s = txtemail.getText();
			String[] splitString = s.split("@");
			if (splitString[1].equalsIgnoreCase("gmail.com")) {
				lblemail.setText("");
			} else
				lblemail.setText(" Invalied Email id");
		}
		if (txtemail.getText().equals(""))
			lblemail.setText("");
	}// GEN-LAST:event_txtemailKeyReleased

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PartnerAddUpdate.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PartnerAddUpdate.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PartnerAddUpdate.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PartnerAddUpdate.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new PartnerAddUpdate().setVisible(true);
			}
		});
	}

}
