package com.yash.pms.view;


import java.beans.Statement;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.yash.pms.dao.PartnerDao;
import com.yash.pms.model.Partner;
import com.yash.pms.util.PartnerConstants;

public class PartnerSearch extends javax.swing.JFrame {
    static String idd;
    /**
     * Creates new form CustomerDetailsBill
     */
    public PartnerSearch() {
        initComponents();
        loadTable();
    }

	public void loadTable() {

		try {
			List<Partner> partnerList = new ArrayList<Partner>();
			partnerList = PartnerDao.getAllPartners();
			// System.out.print(stData);
			int q = partnerList.size();
			DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
			// System.out.print(RecordTable);
			RecordTable.setRowCount(0);

			
			for (Partner p : partnerList) {
				Vector<String> columnData = new Vector<String>();
				for (int i = 1; i <= q; i++) {
				columnData.add(p.getPartnerId());
				columnData.add(p.getFullName());
				columnData.add(p.getOrgType());
				columnData.add(p.getOrgName());
				columnData.add(p.getResources());
				columnData.add(p.getMobile());
				columnData.add(p.getEmail());
				columnData.add(p.getAddress());
				columnData.add(p.getState());
				columnData.add(p.getCity());
				columnData.add(p.getZipCode());
			}
			RecordTable.addRow(columnData);
			// System.out.println(columnData);

		}}
		catch (Exception ex) {
		}
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
      
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        
        jL_search = new javax.swing.JLabel();
        jL_orgtype = new javax.swing.JLabel();        
        jL_orgname = new javax.swing.JLabel();
        comboorgtype = new javax.swing.JComboBox<>();
        txtorgname=new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        setLocation(300, 200);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bill.jpg"))); // NOI18N
        jLabel1.setText("Parner Search Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close-icon-s.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 40, 40));

        
        jL_orgtype.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jL_orgtype.setForeground(new java.awt.Color(255, 255, 255));
        jL_orgtype.setText("Org Type ");
        getContentPane().add(jL_orgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 230, -1));
        
        comboorgtype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboorgtype.setModel(new javax.swing.DefaultComboBoxModel<>(PartnerConstants.Orgtype));
		getContentPane().add(comboorgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 150, 35));
		
		jL_orgname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		jL_orgname.setForeground(new java.awt.Color(255, 255, 255));
		jL_orgname.setText("Org Name ");
        getContentPane().add(jL_orgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 230, -1));

        txtorgname.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtorgname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtorgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 140, 35));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 100, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null,null, null, null, null, null, null, null, null, null, null},
                {null,null, null, null, null, null, null, null, null, null, null},
                {null,null, null, null, null, null, null, null, null, null, null},
                {null,null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Partner Id","Contact Name", "Org Type", "Org name", "Resources","Mobile Number", "Email", "Address", "State", "City", "zipcode"
            }
            ////first_name,last_name,org_type,org_name,email,mobile,resources,address1,state,city,postcode)"
        ) {
            boolean[] canEdit = new boolean [] {
                false,false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1120, 590));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Double Click on row to Print/Email Partner Information");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 500, 42));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jB_ClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 100, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-kmk.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		 
        loadTable();
        comboorgtype.setSelectedIndex(0);
        txtorgname.setText("");
                // TODO add your handling code here:
     }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
if(evt.getClickCount()==2){
   
    DefaultTableModel RecordTable= (DefaultTableModel) jTable1.getModel();
    int SelectedRows=jTable1.getSelectedRow();
    idd=((String) RecordTable.getValueAt(SelectedRows,0));
     new PartnerPrint().setVisible(true);
}              
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
      
        try {
            //Class.forName("org.h2.Driver");
        	
            
            List<Partner> partnerList = new ArrayList<Partner>();
			partnerList = PartnerDao.getSearchPartners(comboorgtype.getItemAt(comboorgtype.getSelectedIndex()),txtorgname.getText());
            
            int q = partnerList.size();
            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            for (Partner p : partnerList) {
				Vector<String> columnData = new Vector<String>();
				for (int i = 1; i <= q; i++) {
				columnData.add(p.getPartnerId());
				columnData.add(p.getFullName());
				columnData.add(p.getOrgType());
				columnData.add(p.getOrgName());
				columnData.add(p.getResources());
				columnData.add(p.getMobile());
				columnData.add(p.getEmail());
				columnData.add(p.getAddress());
				columnData.add(p.getState());
				columnData.add(p.getCity());
				columnData.add(p.getZipCode());
			}
			RecordTable.addRow(columnData);
			// System.out.println(columnData);
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Record Not Found.");
        }
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartnerSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartnerSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartnerSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartnerSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartnerSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
   
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;

    private javax.swing.JTextField txtorgname;
    
    private javax.swing.JLabel jL_search;
    private javax.swing.JLabel jL_orgtype;
    private javax.swing.JLabel jL_orgname;
    private javax.swing.JComboBox<String> comboorgtype;
    // End of variables declaration//GEN-END:variables
}
